import type { Metadata } from 'next';
import '../../globals.css';
import Wrapper from '@/components/shared/Wrapper';

export const metadata: Metadata = {
  title: 'Update todos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen">
      <Wrapper className="mx-auto flex flex-col items-center justify-start">
        {children}
      </Wrapper>
    </div>
  );
}
